server:
  port: 9994

spring:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri:
        user-info-uri: 
        jwk-set-uri: 
        user-name-attribute: 
    client:
      registration:
        cognito:
          scope: 


authentication:
  oauth2:
    jwks: 
    issuer: 